### ISSUE TITLE
Preprocessing is sub-optimal

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#28]
here's suggestion-- please replace with proper variables:

```console
# get centerline
# if it doesn't work, do it manually
sct_get_centerline -i sub-zh48_ses-01_acq-sag_T2w_resample.nii.gz -method viewer -gap 30 -qc qc
# dilate with a square instead of a ball to not include all the crap above and below
sct_maths -i sub-zh48_ses-01_acq-sag_T2w_resample_centerline.nii.gz -dilate 15 -shape square -dim 1 -o sub-zh48_ses-01_acq-sag_T2w_resample_centerline_dil.nii.gz
# crop with mask
# rest is the same...
```

add QC procedure in the README of this repos, namely
- how to correct centerline
- how to upload/name it

Possible other improvements:
- train a better model to detect centerline https://github.com/ivadomed/model_seg_sci/issues/29

**Comment by naga-karthik** [comment]
Just a quick note - I was playing around with different shape values for dilation and it seems that even `-shape disk` also gives similar results to `-shape square` (`-dim 1` is fixed in both cases) after dilation. However, we are fine with using either as long as the spinal cord is getting cropped correctly (which is what is we care about).

**Comment by jcohenadad** [comment]
> even -shape disk also gives similar results to -shape square

yes, it makes sense: max(disk) = max(square)

**Comment by naga-karthik** [comment]
I have used `sct_get_centerline` on all subjects and it turns out that the method has performed quite well! Only 18 out of 80 subjects need manual centerline correction. However, I needed a minor clarification in manually correcting the subjects - Because we're computing the centerline on the resampled images, I noticed that it is easier to select points on the spinal cord while doing `sct_get_centerline -i <(resampled)-subject-name> -method viewer -gap 30 -qc qc`. I also tried manually correcting the centerline on the original images but it is difficult to select points in this case because the axial slices are very thick. Therefore, there are two options here:

1. If I do the manual correction to get the centerline on the **resampled images** (instead of the original images), how should the corresponding derivatives file be named? Something like `<sub-XX_ses-XX_resample_centerline-manual>` or simply as `<sub-XX_ses-XX_centerline-manual>` (despite being corrected on the resampled image)?
2. Do not use the resampled image, do the manual correction on the original image (with thick axial resolution). In this case, the label file will be named `<sub-XX_ses-XX_centerline-manual>` as it is the standard.

**Comment by jcohenadad** [comment]
> I noticed that it is easier to select points on the spinal cord while doing [...]

Easier than what?

**Comment by jcohenadad** [comment]
> I also tried manually correcting the centerline on the original images but it is difficult to select points in this case because the axial slices are very thick.

I'm not sure I understand what the problem is here. Thick axial slices should actually provide the best view of the spinal cord: 

![image](https://user-images.githubusercontent.com/2482071/212781270-83d6e822-3326-43ec-9bd7-31426603c334.png)

**Comment by jcohenadad** [comment]
> 1. If I do the manual correction to get the centerline on the resampled images (instead of the original images), how should the corresponding derivatives file be named? Something like <sub-XX_ses-XX_resample_centerline-manual> or simply as <sub-XX_ses-XX_centerline-manual> (despite being corrected on the resampled image)?
> 2. Do not use the resampled image, do the manual correction on the original image (with thick axial resolution). In this case, the label file will be named <sub-XX_ses-XX_centerline-manual> as it is the standard.

Excellent question! Ultimately we would like an algorithm that finds the centerline on any type of input resolution image, so I am leaning towards doing the ground truth centerline on the native resolution image.

**Comment by naga-karthik** [comment]
Well, most of the subjects on which the method failed were lumbar spinal cord images. I thought it is expected given that the centerline detection model was trained on images consisting of cervical and thoracic scans (as seen in Section 2.2, first para of [this](https://www.sciencedirect.com/science/article/pii/S136184151730186X?via%3Dihub) paper). 

While doing `sct_get_centerline -method viewer`, the GUI that I see for selecting the points is shown below and the points are to be selected on the axial slices. Note that this is the original image (not the resampled one). I was referring to the difficultly in identifying the spinal cord in these images compared to the resampled ones where it is easier to detect the spinal cord in order to select the points on it. 

<img width="1048" alt="Screen Shot 2023-01-16 at 6 51 04 PM" src="https://user-images.githubusercontent.com/53445351/212781809-95e6a541-1179-4d41-b40c-13751d2b412e.png">

> Ultimately we would like an algorithm that finds the centerline on any type of input resolution image, so I am leaning towards doing the ground truth centerline on the native resolution image.

Sounds good, that's also what I had in mind - it would be good to get the centerline on the original resolution images for robustness.

**Comment by jcohenadad** [comment]
> While doing sct_get_centerline -method viewer, the GUI that I see for selecting the points is shown below and the points are to be selected on the axial slices. Note that this is the original image (not the resampled one). I was referring to the difficultly in identifying the spinal cord in these images compared to the resampled ones where it is easier to detect the spinal cord in order to select the points on it.

Right... I agree it is more difficult to find the cord on a low-res image. I guess you'll have to train your brain 😉  Alternatively (for longer term), we should have a feature in the interactive viewer to interpolate the image on display.
