### ISSUE TITLE
Train a model to detect spinal cord centerline

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#29]
Given the importance of cropping the volume for training/inference, a possible strategy would be to train a model to detect the centerline, that would be specific to these image.

**Comment by naga-karthik** [comment]
Based on a brief (water cooler) conversation along with @valosekj, here's a proof-of-concept to test the feasibility of this idea. We could formulate this as a segmentation problem and make the model output the spinal cord (SC) centerlines as segmentation niftis. 

**Rationale?** -  We already get decent outputs from `sct_get_centerline` as binary nifti files containing discretized SC centerlines. Moreover, these are of the same shape as the input image, thereby setting up conveniently as a segmentation problem. Hence, the input to the model will be a T2w sagittal image (initially), and it is trained to output a binarized prediction of the centerline. 

Implementational details that need to be ironed out:
1. Usually, the input image is cropped to a manageable size using the (dilated) centerline or SC mask as the reference. How will the input be cropped if the goal itself is to predict the centerline?
2. Should orientations other _sagittal_ be considered? If so, how? What additional information can they provide?

**Alternative** - If the above idea does not work for some reason, here's an alternative. Instead of posing it as a segmentation problem, pose it as a regression problem. This is because `sct_get_centerline` also outputs a `.csv` file containing the voxel coordinates of the centerline along with binarized nifti. Then, a model is trained to regress these coordinates (3 values) for each slice in the sagittal image (hoping that it would be continuous). A centerline could then be constructed based the predicted voxel coordinates. 

This is a rough sketch of what I had in mind, any suggestions are welcome!

**Comment by valosekj** [comment]
Also relevant https://github.com/ivadomed/canproco/issues/7

**Comment by jcohenadad** [comment]
> Should orientations other sagittal be considered? If so, how? What additional information can they provide?

I'm not sure I understand that part. Did you mean "other _than_ sagittal"? And if so, at what level are you planning to enforce this orientation? Usually a specific orientation is not required (and should not)

**Comment by naga-karthik** [comment]
This is answered in this [issue(comment)](https://github.com/neuropoly/idea-projects/issues/15#issuecomment-1398813501). It would be great if you could follow-up with your latest thoughts on that instead! 

As a result, closing this issue here to avoid duplication.
