### ISSUE TITLE
Create preprocessing pipeline

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#6]
This pipeline will prepare data for training. Notably:

- Segment the spinal cord to extract ROI for cropping
  - Pros: Smaller input volume for training keeping only the spinal cord region in focus. Saves a lot of memory while allowing the possibility of having relatively bigger models.
- Resample to 0.5mm isotropic resolution
  - Pros: will accommodate multiple input resolutions (eg from other domains)
  - Cons: upsampling along directions where resolution is poor (eg: 3mm slice thickness --> 0.5mm)

Get started from the preprocessing here: https://github.com/ivadomed/model_seg_ms_mp2rage
EDIT: Added a Pro supporting SC segmentation

**Comment by naga-karthik** [comment]
Based on a recent discussion, it was concluded that, for now, resampling is not required because the first iteration of the model only uses a single contrast (sagittal-T2w). However, we want to keep this open for the future when a model incorporating multiple contrasts and/or anatomical planes will be trained. In that case, resampling to isotropic resolution will surely help in accomodating more information. 

That said, the resampling value is undecided yet. Currently, the in-plane axial resolution in the sagittal image is high, which makes SC segmentation (and therefore, lesions) difficult. Moreover, training a DL model to segment lesions based on a single sagittal T2w contrast might be an under-utilization of total available information (axial T2w and T1w contrasts). Hence, resampling is important when we want to include more information for model training. More on this soon.
