### ISSUE TITLE
Find a way to exclude subjects with strong artifacts when processing data

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#9]
The 'bad' subjects are listed in the file `exclude.yml`, which was filled after visual QC of the whole dataset.

**Comment by naga-karthik** [comment]
After running the pre-processing script again with the larger `sci-zurich` dataset, I found this subject (`sub-zh78_ses-01`) which has a strong metal artifact which completely threw off sct_deepseg_sc to get the spinal cord segmentation initially. 

<details>

<summary> SCT preprocessing output for `sub-zh78_ses-01` </summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53445351/184411106-23f964bc-5dbe-4932-a545-b7fbc3a3cfa7.gif)

</details>
Note: The cropped image is shown to be brighter than the original image so that they can be distinguished.  

Because of the heavy artifact interference, I will be adding this subject to `exclude.yml`.

**Comment by naga-karthik** [comment]
Closing this as we have moved away from an explicit preprocessing script. In addition, we are not excluding any subjects from the dataset and instead using all of them (despite the presence of metal artifacts)
